### ISSUE TITLE
Unescaped char in CN

### ISSUE THREAD

**Issue by xUndero** [wekan/wekan#4754]
### Server Setup Information
Wekan v6.55 (Docker)

### Problem description
User's CN in AD has chars "()" and while login get that exception:

#### Logs
[DEBUG] Group list filter LDAP: "(&(objectclass=group)(member=CN=Name P. Surname (3),OU=Users,OU=City,DC=domain,DC=com))"
Exception while invoking method 'login' Error: illegal unescaped char: (
    at escapeValue (/build/programs/server/npm/node_modules/ldap-filter/lib/index.js:49:13)
    at parseExpr (/build/programs/server/npm/node_modules/ldap-filter/lib/index.js:167:16)
    at parseFilter (/build/programs/server/npm/node_modules/ldap-filter/lib/index.js:228:14)
    at parseFilter (/build/programs/server/npm/node_modules/ldap-filter/lib/index.js:204:13)
    at Object.parse (/build/programs/server/npm/node_modules/ldap-filter/lib/index.js:252:18)
    at Object.parseString (/build/programs/server/npm/node_modules/ldapjs/lib/filters/index.js:179:27)
    at Client.search (/build/programs/server/npm/node_modules/ldapjs/lib/client/client.js:571:30)
    at LDAP.searchAllAsync (packages/wekan-ldap/server/ldap.js:544:17)
    at LDAP._searchAllSync (packages/meteor.js:306:21)
    at LDAP.searchAllSync (packages/wekan-ldap/server/ldap.js:74:17)
    at LDAP.getUserGroups (packages/wekan-ldap/server/ldap.js:386:25)
    at MethodInvocation.<anonymous> (packages/wekan-ldap/server/loginHandler.js:185:27)
    at packages/accounts-base/accounts_server.js:499:31
    at tryLoginMethod (packages/accounts-base/accounts_server.js:1341:14)
    at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:497:22)
    at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:557:31)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43

**Comment by xet7** [comment]
@xUndero

I don't have LDAP server. Can someone check that:

a) Is that LDAP syntax correct above?

b) Is there something incorrect in WeKan LDAP code here?
https://github.com/wekan/wekan/tree/master/packages/wekan-ldap

**Comment by mfilser** [comment]
I don't know, just an idea: Maybe you can put a backslash before () ?

**Comment by xet7** [comment]
Or, backslash before each character that needs escaping, like:

```
\(\)
```

**Comment by xUndero** [comment]
Hi! Where can i escape? DN field automaticaly get from AD.
Also, In older versions, the escapeValue() function did not define brackets as special char and work fine.(I saw in 3.49)

**Comment by mfilser** [comment]
@xUndero 
I thought you configured the LDAP filter.

@xet7 
I don't have LDAP, so i can't test it too.
Who did develop the LDAP feature? There are a lot of LDAP issues the last time. Maybe there is a good LDAP library for Javascript out there, so it's no need to reindent the wheel

**Comment by xet7** [comment]
@mfilser 

LDAP devs are listed at:
- https://github.com/wekan/ldap/commits/master
- https://github.com/wekan/wekan/pulls?q=is%3Apr+is%3Aclosed+LDAP

@maximest-pierre @guillaume @Akuket @imkwx @alkemyst @GavinLilly @stevenpwaters @svenseeberg @robert-scheck @thiagofernando @tdemaret @pshunter @Trekky12 @KuenzelIT @koelle25 @daMihe @salleman33 @gramakri @indika-dev @luisfcorreia

Hi LDAP devs! What do you think, could you help with these LDAP issues?
- https://github.com/wekan/wekan/issues?q=is%3Aissue+is%3Aopen+LDAP

Current WeKan LDAP code has many fixes and additions to work in various cases. Question is, can additional fixes be made, or is there some even better maintained version of LDAP code somewhere?

To actually do LDAP sync and removing of old users correctly, there is also this Python3 script:
- https://github.com/wekan/wekan/blob/master/ldap-sync/ldap-sync.py

**Comment by gramakri** [comment]
Looks to be related to https://github.com/ldapjs/node-ldapjs/issues/564 . I guess we need to escape it like https://github.com/ldapjs/node-ldapjs/blob/a113953e0d91211eb945d2a3952c84b7af6de41c/lib/filters/index.js#L167-L177

**Comment by gramakri** [comment]
@xet7 Don't think that `escapedToHex` is exported by ldapjs , so the fix won't work.

**Comment by nebulade** [comment]
I just ran our Cloudron e2e tests for wekan and can confirm the LDAP login is now broken with:
```
16:58:32 - Exception while invoking method 'login' ReferenceError: escapedToHex is not defined
16:58:32 - at new LDAP (packages/wekan-ldap/server/ldap.js:32:44)
16:58:32 - at MethodInvocation.<anonymous> (packages/wekan-ldap/server/loginHandler.js:40:16)
16:58:32 - at packages/accounts-base/accounts_server.js:589:31
16:58:32 - at tryLoginMethod (packages/accounts-base/accounts_server.js:1513:14)
16:58:32 - at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:587:22)
16:58:32 - at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:647:31)
16:58:32 - at packages/check/match.js:118:15
16:58:32 - at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1259:12)
16:58:32 - at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
16:58:32 - at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1899:18)
16:58:32 - at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:772:38)
16:58:32 - at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1259:12)
16:58:32 - at packages/ddp-server/livedata_server.js:791:46
16:58:32 - at new Promise (<anonymous>)
16:58:32 - at Session.method (packages/ddp-server/livedata_server.js:739:23)
16:58:32 - at packages/ddp-server/livedata_server.js:603:43
```

Is there some require missing or such?

**Comment by xet7** [comment]
@xUndero @nebulade

Please try WeKan v6.58 , does it work correctly with above fix?

**Comment by xUndero** [comment]
Hi! No
[WARN] Lookup for unset variable: INTERNAL_LOG_LEVEL
[WARN] Lookup for unset variable: LDAP_USER_ATTRIBUTES
Exception while invoking method 'login' TypeError: escapedToHex is not a function
    at new LDAP (packages/wekan-ldap/server/ldap.js:33:44)
    at MethodInvocation.<anonymous> (packages/wekan-ldap/server/loginHandler.js:40:16)
    at packages/accounts-base/accounts_server.js:589:31
    at tryLoginMethod (packages/accounts-base/accounts_server.js:1513:14)
    at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:587:22)
    at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:647:31)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1259:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1899:18)
    at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:772:38)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1259:12)
    at packages/ddp-server/livedata_server.js:791:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:739:23)
    at packages/ddp-server/livedata_server.js:603:43

**Comment by nebulade** [comment]
Indeed looking at the ldapjs code, it seems that function is not exported https://github.com/ldapjs/node-ldapjs/blob/1570e049526fffc47df00615ce48860cf3da77b3/lib/filters/index.js#L166

Maybe we have to go via the parseString() function here.

**Comment by xet7** [comment]
@xUndero @nebulade 

Would it be possible for you to add some kind of escape there somewhere, test that it works, and then submit PR ? I think that without actual LDAP server I'm coding blind, unable to test.

Building WeKan info at https://github.com/wekan/wekan/wiki/Emoji

**Comment by akitzing** [comment]
> [WARN] Lookup for unset variable: INTERNAL_LOG_LEVEL
> [WARN] Lookup for unset variable: LDAP_USER_ATTRIBUTES
> Exception while invoking method 'login' TypeError: escapedToHex is not a function

Same error while updating from 6.50 or 6.54 to 6.58.

**Comment by nebulade** [comment]
Since that function is not exposed in any way from the ldapjs module, I have just copied over those few lines now with https://github.com/wekan/wekan/pull/4760

At least for Cloudron end to end tests, this now works again, although I am a bit sceptical why this is needed in the first place and if not simply one can expect the config variable provided as the ldap search filter also comes in properly escaped.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/4760

**Comment by xUndero** [comment]
Hi! The filter still doesn't work.
Are you using https://github.com/pfmooney/node-ldap-filter?
@pfmooney @melloc What is the reason for filtering by round brackets in function escapeValue?
As I mentioned above, CN can contain round brackets.

**Comment by xet7** [comment]
The error here — `Group list filter LDAP: ... illegal unescaped char: (` thrown from `getUserGroups` when a CN/DN contains parentheses — has been fixed. Commit 6a89da85e (fixing the duplicate report #5236) adds RFC 4515 escaping via `escapeLdapFilterValue` for `( ) * \\ NUL`, applied to the group member-format value in both `getUserGroups` and `isUserInGroup` in packages/wekan-ldap/server/ldap.js (lines 414 and 461). The earlier `escapedToHex is not a function` regression from PR #4760 is also resolved (escapedToHex is now defined at ldap.js:5). Closing as fixed; please reopen if LDAP sign-in with parentheses in the DN still fails on the latest release.
