### ISSUE TITLE
Email notifications show "undefined" instead of username (v8.47+)

### ISSUE THREAD

**Issue by apiccolim** [wekan/wekan#6280]
### Description
Since updating from v8.19 to v8.47, email notifications stopped resolving 
the username correctly. Where the username should appear, the emails show "undefined".

### Expected
Email: "[user] moved card X to list Y"

### Actual
Email: "undefined moved card X to list Y"

### Environment

| Field | Value |
|---|---|
| Wekan version | 8.74.0 |
| Meteor version | 3.4 |
| Node version | 22.22.2 |
| MongoDB version | 8.2.6 |
| MongoDB storage engine | wiredTiger |
| MongoDB Oplog enabled | No |
| OS type | Linux x64 |
| OS version | 6.8.0-106-generic |
| Deployment | Docker |

### Additional context
Last working version: v8.19. Regression started around v8.47.

This may be related to the Meteor 3 migration, where `Meteor.userId()` can return 
`undefined` inside async callbacks if the user context is not properly preserved.

### Steps to Reproduce

1. Have any user perform an action on a card (move, comment, create, archive, etc.)
2. Check the email notification sent by Wekan for that action
3. Observe that the username appears as "undefined" instead of the actual username

### Relevant Logs

```shell
Exception from sub myCards id X5wP7C2WT9iKGJtiv TypeError: Promise.await is not a function
    at Subscription.<anonymous> (webpack:/wekan/server/publications/cards.js:235:25)

RulesHelper.executeRules error for activity jjSToEnD55ifjxKyi TypeError: o.Meteor.userId is not a function
    at _helpersConstructor._helpersConstructor.<anonymous> (webpack:/wekan/models/cards.js:2172:28)
    at _helpersConstructor._helpersConstructor.move (webpack:/wekan/models/cards.js:2211:3)
    at webpack:/wekan/server/rulesHelper.js:122:20
```

**Comment by Raawen-dev** [comment]
Thank you for the detailed logs @apicolim. The key error tells us exactly what broke:

**Error:**

**Root Cause Analysis (for documentation):**

This is a **Meteor 3 migration regression**. In Meteor 3, Fibers were removed and replaced with native async/await. The code at:
- `server/publications/cards.js:235` 
- `models/cards.js:2172`

Still uses old Fibers syntax (`Promise.await`) or assumes synchronous `Meteor.userId()` in async contexts.

**Why username shows "undefined":**
When `Meteor.userId()` fails (returns undefined), the notification system falls back to an empty user object, causing `username` → `undefined` in email templates.

**Code locations needing fixes:**

| File | Line(s) | Issue |
|------|---------|-------|
| `server/publications/cards.js` | 235 | `Promise.await` should be `await` |
| `models/cards.js` | 2172 | Wrap `Meteor.userId()` in `Meteor.bindEnvironment()` or use async context |
| `models/notifications.js` | ~150-200 | Email user lookup needs async/await pattern |

**Temporary workaround for sysadmins:**

Add to your Docker environment (`docker-compose.yml`):
```yaml
environment:
  - METEOR_DISABLE_FIBERS_CHECK=true
```
Or downgrade to v8.19 until fixed.

Documentation update needed:

Add to docs/meteor3-migration.md:

## Common Issues After Migration

### "undefined" username in email notifications

**Symptoms:** Emails show "undefined" instead of usernames

**Cause:** Code using `Promise.await()` or sync `Meteor.userId()` in async callbacks

**Fix:** 
- Replace `Promise.await()` with `await`
- Wrap user context with `Meteor.bindEnvironment()` or pass userId explicitly

**Related errors:**
- `TypeError: Promise.await is not a function`
- `TypeError: Meteor.userId is not a function`

> 

>
