### ISSUE TITLE
Cannot find module '/build/main.js' error in latest docker image

### ISSUE THREAD

**Issue by s8321414** [wekan/wekan#6291]
### Bug Description

When I upgrade from v8.74 to v8.94 using docker image, it will show module not found error.
Rollback to v8.74 then just works.

### Steps to Reproduce

1. Upgrade v8.74 to v8.94
2. Check output of `docker compose logs`

### Relevant Logs

```shell
wekan-app  | node:internal/modules/cjs/loader:1459
wekan-app  |   throw err;
wekan-app  |   ^
wekan-app  | 
wekan-app  | Error: Cannot find module '/build/main.js'
wekan-app  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1456:15)
wekan-app  |     at defaultResolveImpl (node:internal/modules/cjs/loader:1066:19)
wekan-app  |     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1071:22)
wekan-app  |     at Module._load (node:internal/modules/cjs/loader:1242:25)
wekan-app  |     at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
wekan-app  |     at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
wekan-app  |     at node:internal/main/run_main_module:33:47 {
wekan-app  |   code: 'MODULE_NOT_FOUND',
wekan-app  |   requireStack: []
wekan-app  | }
wekan-app  | 
wekan-app  | Node.js v24.14.1
wekan-app  | node:internal/modules/cjs/loader:1459
wekan-app  |   throw err;
wekan-app  |   ^
wekan-app  | 
wekan-app  | Error: Cannot find module '/build/main.js'
wekan-app  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1456:15)
wekan-app  |     at defaultResolveImpl (node:internal/modules/cjs/loader:1066:19)
wekan-app  |     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1071:22)
wekan-app  |     at Module._load (node:internal/modules/cjs/loader:1242:25)
wekan-app  |     at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
wekan-app  |     at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
wekan-app  |     at node:internal/main/run_main_module:33:47 {
wekan-app  |   code: 'MODULE_NOT_FOUND',
wekan-app  |   requireStack: []
wekan-app  | }
wekan-app  | 
wekan-app  | Node.js v24.14.1
wekan-app  | node:internal/modules/cjs/loader:1459
wekan-app  |   throw err;
wekan-app  |   ^
wekan-app  | 
wekan-app  | Error: Cannot find module '/build/main.js'
wekan-app  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1456:15)
wekan-app  |     at defaultResolveImpl (node:internal/modules/cjs/loader:1066:19)
wekan-app  |     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1071:22)
wekan-app  |     at Module._load (node:internal/modules/cjs/loader:1242:25)
wekan-app  |     at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
wekan-app  |     at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
wekan-app  |     at node:internal/main/run_main_module:33:47 {
wekan-app  |   code: 'MODULE_NOT_FOUND',
wekan-app  |   requireStack: []
wekan-app  | }
wekan-app  | 
wekan-app  | Node.js v24.14.1
wekan-app  | node:internal/modules/cjs/loader:1459
wekan-app  |   throw err;
wekan-app  |   ^
wekan-app  | 
wekan-app  | Error: Cannot find module '/build/main.js'
wekan-app  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1456:15)
wekan-app  |     at defaultResolveImpl (node:internal/modules/cjs/loader:1066:19)
wekan-app  |     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1071:22)
wekan-app  |     at Module._load (node:internal/modules/cjs/loader:1242:25)
wekan-app  |     at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
wekan-app  |     at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
wekan-app  |     at node:internal/main/run_main_module:33:47 {
wekan-app  |   code: 'MODULE_NOT_FOUND',
wekan-app  |   requireStack: []
wekan-app  | }
wekan-app  | 
wekan-app  | Node.js v24.14.1
wekan-app  | node:internal/modules/cjs/loader:1459
wekan-app  |   throw err;
wekan-app  |   ^
wekan-app  | 
wekan-app  | Error: Cannot find module '/build/main.js'
wekan-app  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1456:15)
wekan-app  |     at defaultResolveImpl (node:internal/modules/cjs/loader:1066:19)
wekan-app  |     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1071:22)
wekan-app  |     at Module._load (node:internal/modules/cjs/loader:1242:25)
wekan-app  |     at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
wekan-app  |     at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
wekan-app  |     at node:internal/main/run_main_module:33:47 {
wekan-app  |   code: 'MODULE_NOT_FOUND',
wekan-app  |   requireStack: []
wekan-app  | }
wekan-app  | 
wekan-app  | Node.js v24.14.1
wekan-app  | node:internal/modules/cjs/loader:1459
wekan-app  |   throw err;
wekan-app  |   ^
wekan-app  | 
wekan-app  | Error: Cannot find module '/build/main.js'
wekan-app  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1456:15)
wekan-app  |     at defaultResolveImpl (node:internal/modules/cjs/loader:1066:19)
wekan-app  |     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1071:22)
wekan-app  |     at Module._load (node:internal/modules/cjs/loader:1242:25)
wekan-app  |     at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
wekan-app  |     at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
wekan-app  |     at node:internal/main/run_main_module:33:47 {
wekan-app  |   code: 'MODULE_NOT_FOUND',
wekan-app  |   requireStack: []
wekan-app  | }
wekan-app  | 
wekan-app  | Node.js v24.14.1
wekan-app  | node:internal/modules/cjs/loader:1459
wekan-app  |   throw err;
wekan-app  |   ^
wekan-app  | 
wekan-app  | Error: Cannot find module '/build/main.js'
wekan-app  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1456:15)
wekan-app  |     at defaultResolveImpl (node:internal/modules/cjs/loader:1066:19)
wekan-app  |     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1071:22)
wekan-app  |     at Module._load (node:internal/modules/cjs/loader:1242:25)
wekan-app  |     at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
wekan-app  |     at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
wekan-app  |     at node:internal/main/run_main_module:33:47 {
wekan-app  |   code: 'MODULE_NOT_FOUND',
wekan-app  |   requireStack: []
wekan-app  | }
wekan-app  | 
wekan-app  | Node.js v24.14.1
wekan-app  | node:internal/modules/cjs/loader:1459
wekan-app  |   throw err;
wekan-app  |   ^
wekan-app  | 
wekan-app  | Error: Cannot find module '/build/main.js'
wekan-app  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1456:15)
wekan-app  |     at defaultResolveImpl (node:internal/modules/cjs/loader:1066:19)
wekan-app  |     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1071:22)
wekan-app  |     at Module._load (node:internal/modules/cjs/loader:1242:25)
wekan-app  |     at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
wekan-app  |     at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
wekan-app  |     at node:internal/main/run_main_module:33:47 {
wekan-app  |   code: 'MODULE_NOT_FOUND',
wekan-app  |   requireStack: []
wekan-app  | }
wekan-app  | 
wekan-app  | Node.js v24.14.1
wekan-app  | node:internal/modules/cjs/loader:1459
wekan-app  |   throw err;
wekan-app  |   ^
wekan-app  | 
wekan-app  | Error: Cannot find module '/build/main.js'
wekan-app  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1456:15)
wekan-app  |     at defaultResolveImpl (node:internal/modules/cjs/loader:1066:19)
wekan-app  |     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1071:22)
wekan-app  |     at Module._load (node:internal/modules/cjs/loader:1242:25)
wekan-app  |     at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
wekan-app  |     at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
wekan-app  |     at node:internal/main/run_main_module:33:47 {
wekan-app  |   code: 'MODULE_NOT_FOUND',
wekan-app  |   requireStack: []
wekan-app  | }
wekan-app  | 
wekan-app  | Node.js v24.14.1
```
