### ISSUE TITLE
Release, v0.10.1 does not compile with node v6.2.1

### ISSUE THREAD

**Issue by m4s0fd1s** [wekan/wekan#634]
Hi, I read that v0.10.40 is required, but it would be awesome if also compiles with newer node versions...

Here's the error output log :

> node ./build.js

(node:42849) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:132:44: error: too many arguments to function call, expected at most 2, have 4
                return Signature::New(isolate, receiver, argc, argv);
                       ~~~~~~~~~~~~~~                    ^~~~~~~~~~
/Users/testuser/.node-gyp/6.2.1/include/node/v8.h:4798:3: note: 'New' declared here
  static Local<Signature> New(
  ^
../src/fibers.cc:140:3: error: no member named 'SetResourceConstraints' in namespace 'v8'; did you mean simply 'SetResourceConstraints'?
                v8::SetResourceConstraints(isolate, constraints);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
                SetResourceConstraints
../src/fibers.cc:139:7: note: 'SetResourceConstraints' declared here
        void SetResourceConstraints(Isolate\* isolate, ResourceConstraints\* constraints) {
             ^
../src/fibers.cc:428:6: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]
                                        delete data;
                                        ^
                                              []
../src/fibers.cc:423:19: note: allocated with 'new[]' here
                                void*\* data = new void_[2];
                                              ^
1 warning and 2 errors generated.
make: *_\* [Release/obj.target/fibers/src/fibers.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/testuser/Downloads/bundle 2/programs/server/node_modules/fibers
gyp ERR! node -v v6.2.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
Build failed
meteor-dev-bundle@0.0.0 /Users/testuser/Downloads/bundle 2/programs/server
├─┬ chalk@0.5.1
│ ├── ansi-styles@1.1.0
│ ├── escape-string-regexp@1.0.3
│ ├─┬ has-ansi@0.1.0
│ │ └── ansi-regex@0.2.1
│ ├── strip-ansi@0.3.0
│ └── supports-color@0.2.0
├─┬ eachline@2.3.3
│ └── type-of@2.0.1
├─┬ meteor-promise@0.5.0
│ └─┬ promise@7.0.4
│   └── asap@2.0.3
├── semver@4.1.0
├─┬ source-map-support@0.3.2
│ └─┬ source-map@0.1.32
│   └── amdefine@1.0.0
└── underscore@1.5.2

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

**Comment by AlexanderS** [comment]
This is a limitation of meteor. See meteor/meteor#7218.

**Comment by AlexanderS** [comment]
meteor 1.4 was release recently. After upgrading we will support node-4.4.7.

**Comment by HLFH** [comment]
https://github.com/meteor/meteor/releases ; could you support it?

**Comment by HLFH** [comment]
FY, on the 1st October the Node.js Foundation will end support for Node.js v0.10.

**Comment by xet7** [comment]
Meteor does not support Node v6 yet.
