### ISSUE TITLE
Regression: Card member selection interface broken

### ISSUE THREAD

**Issue by brlin-tw** [wekan/wekan#6076]
### Bug Description

Hello, after upgrading Wekan to 8.21 from 8.19 we noticed that the card member selection interface now enumerates invalid entries:

<img width="552" height="469" alt="Image" src="https://github.com/user-attachments/assets/ae86faae-a55a-4fa8-a85f-1229bbe6bf5e" />

### Platform / Installation Method

Docker

### CPU

amd64

### Steps to Reproduce

1. Open a card
2. In the Members field, click the + icon to add a new member
3. Observe the member list

### Relevant Logs

```shell
Exception from Tracker afterFlush function: bd34d391402237fe9e986a5b15da4f68c4cea138.js:1:7153
TypeError: $(...).summernote is not a function bd34d391402237fe9e986a5b15da4f68c4cea138.js:1:7153
e/onRendered/<@https://wekan.ossii.com.tw/bd34d391402237fe9e986a5b15da4f68c4cea138.js?meteor_js_resource=true:508:649255
each@https://wekan.ossii.com.tw/bd34d391402237fe9e986a5b15da4f68c4cea138.js?meteor_js_resource=true:143:3081
each@https://wekan.ossii.com.tw/bd34d391402237fe9e986a5b15da4f68c4cea138.js?meteor_js_resource=true:143:1560
onRendered@https://wekan.ossii.com.tw/bd34d391402237fe9e986a5b15da4f68c4cea138.js?meteor_js_resource=true:508:649225
onRendered@https://wekan.ossii.com.tw/bd34d391402237fe9e986a5b15da4f68c4cea138.js?meteor_js_resource=true:476:24402
e/f/<@https://wekan.ossii.com.tw/bd34d391402237fe9e986a5b15da4f68c4cea138.js?meteor_js_resource=true:253:36536
e/c._withTemplateInstanceFunc@https://wekan.ossii.com.tw/bd34d391402237fe9e986a5b15da4f68c4cea138.js?meteor_js_resource=true:253:39789
f@https://wekan.ossii.com.tw/bd34d391402237fe9e986a5b15da4f68c4cea138.js?meteor_js_resource=true:253:36439
e/c.prototype.constructView/<@https://wekan.ossii.com.tw/bd34d391402237fe9e986a5b15da4f68c4cea138.js?meteor_js_resource=true:253:37422
t/d.View.prototype.onViewReady/n/</<@https://wekan.ossii.com.tw/bd34d391402237fe9e986a5b15da4f68c4cea138.js?meteor_js_resource=true:253:18537
t/d._withCurrentView@https://wekan.ossii.com.tw/bd34d391402237fe9e986a5b15da4f68c4cea138.js?meteor_js_resource=true:253:23492
t/d.View.prototype.onViewReady/n/<@https://wekan.ossii.com.tw/bd34d391402237fe9e986a5b15da4f68c4cea138.js?meteor_js_resource=true:253:18504
n/o._runFlush@https://wekan.ossii.com.tw/bd34d391402237fe9e986a5b15da4f68c4cea138.js?meteor_js_resource=true:231:3746
a@https://wekan.ossii.com.tw/bd34d391402237fe9e986a5b15da4f68c4cea138.js?meteor_js_resource=true:1:3622
EventListener.handleEvent*r@https://wekan.ossii.com.tw/bd34d391402237fe9e986a5b15da4f68c4cea138.js?meteor_js_resource=true:1:3668
@https://wekan.ossii.com.tw/bd34d391402237fe9e986a5b15da4f68c4cea138.js?meteor_js_resource=true:1:3933
@https://wekan.ossii.com.tw/bd34d391402237fe9e986a5b15da4f68c4cea138.js?meteor_js_resource=true:1:3943
@https://wekan.ossii.com.tw/bd34d391402237fe9e986a5b15da4f68c4cea138.js?meteor_js_resource=true:1:10121
```

### Additional Context

No new entries appear in the browser console while triggering the interface.

**Comment by xet7** [comment]
I'm currently in progress of trying to fix this. When I get it working, I will make new release of WeKan. Also, I'm trying to fix Add Member to board Search.
