### PR TITLE
openapi: fix breakage introduced with blank return

### LINKED ISSUE #5320: Generating WeKan 7.32 OpenAPI docs does not work
@bentiss

Hi ! Do you have time to fix generating WeKan OpenAPI docs?

```
mantic@m:~/repos/wekan$ cat /etc/issue
Ubuntu 23.10 \n \l
mantic@m:~/repos/wekan$ ./releases/rebuild-docs.sh 7.32
Generating package lists... Ready
Generating dependencies tree... Ready
Reading state info... Ready                  
python3-pip is already newest version (23.2+dfsg-1ubuntu0.1).
python3-swagger-spec-validator is already newest version (3.0.3-1).
python3-wheel is already newest version (0.41.0-2).
python3-setuptools is already newest version (68.1.2-2).
0 updated, 0 new install, 0 to remove and 0 not updated.
npm WARN deprecated highlightjs@9.16.2: Use the 'highlight.js' package instead https://npm.im/highlight.js
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated mkdirp-promise@1.1.0: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
/usr/local/bin/api2html -> /usr/local/lib/node_modules/api2html/bin/api2html.js

> core-js@3.36.0 postinstall /usr/local/lib/node_modules/api2html/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting core-js:
> https://opencollective.com/core-js 
> https://patreon.com/zloirock 
> https://boosty.to/zloirock 
> bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz 

I highly recommend reading this: https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/api2html/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ api2html@0.4.0
added 2 packages from 1 contributor and updated 18 packages in 15.981s


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New major version of npm available! 6.14.17 → 10.2.5      │
   │   Changelog: https://github.com/npm/cli/releases/tag/v10.2.5   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

Cloning into 'esprima-python'...
remote: Enumerating objects: 3203, done.
remote: Counting objects: 100% (3203/3203), done.
remote: Compressing objects: 100% (545/545), done.
remote: Total 3203 (delta 1148), reused 3167 (delta 1139), pack-reused 0
Receiving objects: 100% (3203/3203), 7.32 MiB | 21.12 MiB/s, done.
Resolving deltas: 100% (1148/1148), done.
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), 728 bytes | 242.00 KiB/s, done.
From https://github.com/Kronuz/esprima-python
 * [new ref]         refs/pull/20/head -> delete_fix
Switched to branch 'delete_fix'
/usr/lib/python3/dist-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/esprima-0.1.dev2+ga72db28-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
/home/mantic/python/esprima-python/.eggs/setuptools_scm-8.0.4-py3.11.egg/setuptools_scm/git.py:163: UserWarning: "/home/mantic/python/esprima-python" is shallow and may cause errors
  warnings.warn(f'"{wd.path}" is shallow and may cause errors')
running install
/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating esprima.egg-info
writing esprima.egg-info/PKG-INFO
writing dependency_links to esprima.egg-info/dependency_links.txt
writing entry points to esprima.egg-info/entry_points.txt
writing top-level names to esprima.egg-info/top_level.txt
writing manifest file 'esprima.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE.BSD'
writing manifest file 'esprima.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/esprima
copying esprima/nodes.py -> build/lib/esprima
copying esprima/error_handler.py -> build/lib/esprima
copying esprima/character.py -> build/lib/esprima
copying esprima/objects.py -> build/lib/esprima
copying esprima/esprima.py -> build/lib/esprima
copying esprima/scanner.py -> build/lib/esprima
copying esprima/__init__.py -> build/lib/esprima
copying esprima/messages.py -> build/lib/esprima
copying esprima/comment_handler.py -> build/lib/esprima
copying esprima/compat.py -> build/lib/esprima
copying esprima/xhtml_entities.py -> build/lib/esprima
copying esprima/token.py -> build/lib/esprima
copying esprima/utils.py -> build/lib/esprima
copying esprima/visitor.py -> build/lib/esprima
copying esprima/syntax.py -> build/lib/esprima
copying esprima/jsx_parser.py -> build/lib/esprima
copying esprima/__main__.py -> build/lib/esprima
copying esprima/parser.py -> build/lib/esprima
copying esprima/tokenizer.py -> build/lib/esprima
copying esprima/jsx_nodes.py -> build/lib/esprima
copying esprima/jsx_syntax.py -> build/lib/esprima
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/nodes.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/error_handler.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/character.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/objects.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/esprima.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/scanner.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/__init__.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/messages.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/comment_handler.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/compat.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/xhtml_entities.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/token.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/utils.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/visitor.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/syntax.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/jsx_parser.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/__main__.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/parser.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/tokenizer.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/jsx_nodes.py -> build/bdist.linux-x86_64/egg/esprima
copying build/lib/esprima/jsx_syntax.py -> build/bdist.linux-x86_64/egg/esprima
byte-compiling build/bdist.linux-x86_64/egg/esprima/nodes.py to nodes.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/error_handler.py to error_handler.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/character.py to character.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/objects.py to objects.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/esprima.py to esprima.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/scanner.py to scanner.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/messages.py to messages.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/comment_handler.py to comment_handler.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/compat.py to compat.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/xhtml_entities.py to xhtml_entities.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/token.py to token.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/utils.py to utils.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/visitor.py to visitor.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/syntax.py to syntax.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/jsx_parser.py to jsx_parser.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/__main__.py to __main__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/parser.py to parser.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/tokenizer.py to tokenizer.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/jsx_nodes.py to jsx_nodes.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/esprima/jsx_syntax.py to jsx_syntax.cpython-311.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying esprima.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying esprima.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying esprima.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying esprima.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying esprima.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/esprima-0.1.dev2+ga72db28-py3.11.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing esprima-0.1.dev2+ga72db28-py3.11.egg
Removing /usr/local/lib/python3.11/dist-packages/esprima-0.1.dev2+ga72db28-py3.11.egg
Copying esprima-0.1.dev2+ga72db28-py3.11.egg to /usr/local/lib/python3.11/dist-packages
Adding esprima 0.1.dev2+ga72db28 to easy-install.pth file
Installing esprima script to /usr/local/bin

Installed /usr/local/lib/python3.11/dist-packages/esprima-0.1.dev2+ga72db28-py3.11.egg
Processing dependencies for esprima==0.1.dev2+ga72db28
Finished processing dependencies for esprima==0.1.dev2+ga72db28
writing list of installed files to 'files.txt'
Traceback (most recent call last):
  File "/home/mantic/repos/wekan/./openapi/generate_openapi.py", line 1076, in <module>
    main()
  File "/home/mantic/repos/wekan/./openapi/generate_openapi.py", line 1071, in main
    schemas, entry_points = parse_schemas(args.dir)
                            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mantic/repos/wekan/./openapi/generate_openapi.py", line 868, in parse_schemas
    schema_entry_points = [EntryPoint(schemas[current_schema], d)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mantic/repos/wekan/./openapi/generate_openapi.py", line 868, in <listcomp>
    schema_entry_points = [EntryPoint(schemas[current_schema], d)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mantic/repos/wekan/./openapi/generate_openapi.py", line 138, in __init__
    get_req_body_elems(self.body, self.body_params)
  File "/home/mantic/repos/wekan/./openapi/generate_openapi.py", line 19, in get_req_body_elems
    get_req_body_elems(obj.body, elems)
  File "/home/mantic/repos/wekan/./openapi/generate_openapi.py", line 22, in get_req_body_elems
    get_req_body_elems(s, elems)
  File "/home/mantic/repos/wekan/./openapi/generate_openapi.py", line 62, in get_req_body_elems
    get_req_body_elems(obj.consequent, elems)
  File "/home/mantic/repos/wekan/./openapi/generate_openapi.py", line 22, in get_req_body_elems
    get_req_body_elems(s, elems)
  File "/home/mantic/repos/wekan/./openapi/generate_openapi.py", line 69, in get_req_body_elems
    get_req_body_elems(obj.argument, elems)
  File "/home/mantic/repos/wekan/./openapi/generate_openapi.py", line 18, in get_req_body_elems
    if obj.type in ['FunctionExpression', 'ArrowFunctionExpression']:
       ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'type'
✓ Read source file!
✗ Error during conversion via Widdershin:
Cannot read property 'swagger' of undefined
```

### PR DESCRIPTION
**Pull request by bentiss**
Introduced by commit f8ef2e33de2d ("cards.js Added a control to check error if card is not updated"), a blank return was added at line 3914.

The generate_openapi script assumed a return statement always has an argument, and this was crashing.

Fixes #5320

### CODE REVIEW

**Comment by bentiss** [comment]
Actually, I should probably retrun a string in that case, please hold

**Comment by bentiss** [comment]
> Actually, I should probably retrun a string in that case, please hold

Nah, seems to be the exact same output, so we should be good! :)
