### ISSUE TITLE
WeKan v8.43: Cannot find module '@meteorjs/reify/lib/runtime'

### ISSUE THREAD

**Issue by BabyFnord** [wekan/wekan#6224]
### Bug Description

# Server Setup Information
WeKan version: v8.43 (was 8.42 before)
Did you configure root-url correctly so Wekan cards open correctly? Yes.
Operating System: Linux 3.10.0-1160.139.1.el7.tuxcare.els3.x86_64
Deployment Method: bundle
Http frontend if any: Nginx
Meteor-Version: (2.16 in v8.42)
Node.js Version: 14.21.4
MongoDB Version: 5.0.32
Webbrowser: Safari 26.0.1 (19622.1.22.118.4)

# Problem description
After upgrading from 8.42 → 8.43 and starting the service, I get a 502 … Please refer to the supervisord.log content below …

Wondering how to fix this? Could you please help, @xet7 ?
Thank you, BF

### Steps to Reproduce

Start wekan service …

### Relevant Logs

```shell
2026-03-28 09:55:25,834 DEBG 'wekan' stderr output:
internal/modules/cjs/loader.js:936
  throw err;
  ^

Error: Cannot find module '@meteorjs/reify/lib/runtime'
Require stack:
- /home/USER/wekan/wekan-8.43/bundle/programs/server/runtime.js
- /home/USER/wekan/wekan-8.43/bundle/main.js
    at FunctUSER.Module._resolveFilename (internal/modules/cjs/loader.js:933:15)
    at FunctUSER.Module._load (internal/modules/cjs/loader.js:776:27)
    at Module.require (internal/modules/cjs/loader.js:1005:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at enable (/home/USER/wekan/wekan-8.43/bundle/programs/server/runtime.js:34:5)
    at Object.<anonymous> (/home/USER/wekan/wekan-8.43/bundle/main.js:4:40)
    at Module._compile (internal/modules/cjs/loader.js:1116:14)
    at Object.Module._extensUSERs..js (internal/modules/cjs/loader.js:1145:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at FunctUSER.Module._load (internal/modules/cjs/loader.js:821:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/USER/wekan/wekan-8.43/bundle/programs/server/runtime.js',
    '/home/USER/wekan/wekan-8.43/bundle/main.js'
  ]
}
```

**Comment by BabyFnord** [comment]
After reverting back to 8.42, WeKan is up & running again.

**Comment by mzch** [comment]
I happned to encounter this MODULE_NOT_FOUND error (using bundle), too. The 8.43 release doesn't have `bundle/programs/server/node_modules`.
Follow steps below, and this error will be fixed.

1. cd `bundle/programs/server/`
2. npm install

**Comment by BabyFnord** [comment]
Thanks @mzch … I've now installed v8.44, which appears not to throw a 502 at this moment. Checking the log, I see the same error coming continously. I tried your steps, but `npm` doesn't work:
```
[USER@SERVER node_modules]$ npm install

> fibers@5.0.3 install
> node build.js || nodejs build.js

gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@20.20.1 | linux | x64
gyp info find Python using Python versUSER 3.6.8 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v20.20.1/node-v20.20.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v20.20.1/node-v20.20.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v20.20.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v20.20.1/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/USER/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/USER/wekan/wekan-8.44/bundle/programs/server/node_modules/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/USER/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/USER/.cache/node-gyp/20.20.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/USER/.cache/node-gyp/20.20.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/USER/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/USER/.cache/node-gyp/20.20.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/USER/wekan/wekan-8.44/bundle/programs/server/node_modules',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/USER/wekan/wekan-8.44/bundle/programs/server/node_modules/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc: In functUSER ‘void uni::MakeWeak(v8::Isolate*, v8::Persistent<T>&, P*)’:
../src/fibers.cc:27:65: error: ‘kFinalizer’ is not a member of ‘v8::WeakCallbackType’
   27 |   handle.SetWeak(val, WeakCallbackShim<F, P>, WeakCallbackType::kFinalizer);
      |                                                                 ^~~~~~~~~~
../src/fibers.cc: In functUSER ‘void uni::SetAccessor(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, uni::FunctUSERType (*)(v8::Local<v8::String>, const GetterCallbackInfo&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&))’:
../src/fibers.cc:355:87: warning: cast between incompatible functUSER types from ‘uni::FunctUSERType (*)(v8::Local<v8::String>, const GetterCallbackInfo&)’ {aka ‘void (*)(v8::Local<v8::String>, const v8::PropertyCallbackInfo<v8::Value>&)’} to ‘v8::AccessorNameGetterCallback’ {aka ‘void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’} [-Wcast-functUSER-type]
  355 |   object->SetAccessor(isolate->GetCurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter).ToChecked();
      |                                                                                       ^~~~~~
../src/fibers.cc:355:123: warning: cast between incompatible functUSER types from ‘void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&)’ {aka ‘void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’} to ‘v8::AccessorNameSetterCallback’ {aka ‘void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’} [-Wcast-functUSER-type]
  355 |   object->SetAccessor(isolate->GetCurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter).ToChecked();
      |                                                                                                                           ^~~~~~
In file included from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
../src/fibers.cc: At global scope:
/home/USER/.cache/node-gyp/20.20.1/include/node/node.h:1227:43: warning: cast between incompatible functUSER types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-functUSER-type]
 1227 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/USER/.cache/node-gyp/20.20.1/include/node/node.h:1261:3: note: in expansUSER of macro ‘NODE_MODULE_X’
 1261 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/fibers.cc:930:1: note: in expansUSER of macro ‘NODE_MODULE’
  930 | NODE_MODULE(fibers, init)
      | ^~~~~~~~~~~
make: *** [fibers.target.mk:120: Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory '/home/USER/wekan/wekan-8.44/bundle/programs/server/node_modules/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/USER/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:524:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Linux 3.10.0-1160.139.1.el7.tuxcare.els3.x86_64
gyp ERR! command "/opt/nodejs20/bin/node" "/home/USER/node_modules/.bin/node-gyp" "rebuild" "--release"
gyp ERR! cwd /home/USER/wekan/wekan-8.44/bundle/programs/server/node_modules
gyp ERR! node -v v20.20.1
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node versUSER. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructUSERs here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm notice
npm notice New major version of npm available! 9.6.4 -> 11.12.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.12.1
npm notice Run npm install -g npm@11.12.1 to update!
npm notice
npm ERR! code 127
npm ERR! path /home/USER/wekan/wekan-8.44/bundle/programs/server/node_modules
npm ERR! command failed
npm ERR! command sh -c node build.js || nodejs build.js

npm ERR! A complete log of this run can be found in: /home/USER/.npm/_logs/2026-03-30T20_19_25_266Z-debug-0.log
```
This is beyond what I understand. As my log is continuously flooded with the above error (relevant logs in OP), I once again reverted to v8.42.

**Comment by xet7** [comment]
WeKan uses Meteor 3, Node.js 22.22.2, MongoDB 7.x .

Not fibers, not node-gyp. Those are old Meteor 2 stuff.

**Comment by BabyFnord** [comment]
> WeKan uses Meteor 3, Node.js 22.22.2, MongoDB 7.x .

We're not reliant on that custom Node.js v14.21.3 anymore?

**Comment by xet7** [comment]
@BabyFnord 

That's correct.

https://github.com/wekan/wekan/blob/main/CHANGELOG.md#v843-2026-03-27-wekan--release

**Comment by xet7** [comment]
@BabyFnord 

Currently I'm trying to release WeKan v8.44. I tried to make GitHub Actions to build releases, but it did not work, so I will build releases manually with build scripts.

**Comment by s8321414** [comment]
Still doesn't work for v8.45 (in Docker container), rollback to v8.42 is fine.

**Comment by xet7** [comment]
@s8321414

Yes. I just added some missing dependencies to builds. Currently I'm building release v8.46.

**Comment by xet7** [comment]
Actually, release 8.47.

**Comment by s8321414** [comment]
Well, still same error in v8.47 for docker version...

**Comment by xet7** [comment]
@s8321414

Yes. I at v8.47 I again tried to fix GitHub Actions builds, and again it did not work, so I had to comment out all that, and now I really try build every .zip bundle manually, separately, and upload them to release page, one by one, to release v8.48.

**Comment by xet7** [comment]
It seems, that I can start bundle version of WeKan, but Docker and Snap just refuse to co-operate. I'll try again sometime later.

**Comment by s8321414** [comment]
Yes, still no luck with v8.48 in Docker container.

**Comment by BabyFnord** [comment]
❗️ I'm using the bundle version, not Docker.

I tried 8.48 with Node.js v22.22.1 but no luck. While it apparently does start, I get a 502 again as it seems to be stuck in a loop: 
```

2026-03-31 10:53:53,664 DEBG 'wekan' stderr output:
/home/USER/wekan/start-wekan.sh: line 545: 30901 Killed                  node main.js

2026-03-31 10:53:54,096 DEBG 'mongodb' stdout output:
{"t":{"$date":"2026-03-31T10:53:54.072+02:00"},"s":"I",  "c":"COMMAND",  "id":51803,   "ctx":"conn1365","msg":"Slow query","attr":{"type":"command","ns":"wekan.cronJobQueue","command":{"aggregate":"cronJobQueue","pipeline":[{"$match":{"status":"running"}},{"$group":{"_id":1,"n":{"$sum":1}}}],"cursor":{},"lsid":{"id":{"$uuid":"6bcfabeb-139a-4546-80fc-1cf51d5f232b"}},"$db":"wekan"},"planSummary":"COUNT_SCAN { status: 1 }","keysExamined":6,"docsExamined":0,"cursorExhausted":true,"numYields":2,"nreturned":1,"queryHash":"E6304EB6","planCacheKey":"EA72CF1E","reslen":131,"locks":{"FeatureCompatibilityVersUSER":{"acquireCount":{"r":4}},"Global":{"acquireCount":{"r":4}},"Mutex":{"acquireCount":{"r":2}}},"storage":{},"remote":"127.0.0.1:53070","protocol":"op_msg","duratUSERMillis":262}}

2026-03-31 10:53:57,125 DEBG 'wekan' stderr output:
/home/USER/wekan/start-wekan.sh: line 545: 30919 Killed                  node main.js
```

Using Node.js 14.21.4 doesn't make a difference except for reporting it needs Node.js 18 and up. Then I tried 8.42 with Node.js v22.22.1, still no luck, 502 again:
```
Node.js v22.22.1

2026-03-31 10:46:49,905 DEBG 'wekan' stderr output:
## There is an issue with `node-fibers` ##
`/home/USER/wekan/wekan-8.42/bundle/programs/server/node_modules/fibers/bin/linux-x64-127-glibc/fibers.node` is missing.

Try running this to fix the issue: /opt/nodejs22/bin/node /home/USER/wekan/wekan-8.42/bundle/programs/server/node_modules/fibers/build

2026-03-31 10:46:49,905 DEBG 'wekan' stderr output:
Error: Cannot find module '/home/USER/wekan/wekan-8.42/bundle/programs/server/node_modules/fibers/bin/linux-x64-127-glibc/fibers'
Require stack:
- /home/USER/wekan/wekan-8.42/bundle/programs/server/node_modules/fibers/fibers.js
- /home/USER/wekan/wekan-8.42/bundle/programs/server/boot.js
- /home/USER/wekan/wekan-8.42/bundle/main.js
    at FunctUSER._resolveFilename (node:internal/modules/cjs/loader:1383:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
    at FunctUSER._load (node:internal/modules/cjs/loader:1192:37)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
    at Module.require (node:internal/modules/cjs/loader:1463:12)
    at require (node:internal/modules/helpers:147:16)
    at Object.<anonymous> (/home/USER/wekan/wekan-8.42/bundle/programs/server/node_modules/fibers/fibers.js:14:39)
    at Module.<anonymous> (node:internal/modules/cjs/loader:1705:14)

2026-03-31 10:46:49,909 DEBG 'wekan' stderr output:
/home/USER/wekan/wekan-8.42/bundle/programs/server/node_modules/fibers/fibers.js:23
                throw new Error('Missing binary. See message above.');
                ^

Error: Missing binary. See message above.
    at Object.<anonymous> (/home/USER/wekan/wekan-8.42/bundle/programs/server/node_modules/fibers/fibers.js:23:9)
    at Module.<anonymous> (node:internal/modules/cjs/loader:1705:14)
    at Mp._compile (/home/USER/wekan/wekan-8.42/bundle/programs/server/runtime.js:77:23)
    at Object..js (node:internal/modules/cjs/loader:1838:10)
    at Module.<anonymous> (node:internal/modules/cjs/loader:1441:32)
    at Mp.load (/home/USER/wekan/wekan-8.42/bundle/programs/server/runtime.js:37:33)
    at FunctUSER._load (node:internal/modules/cjs/loader:1263:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
    at Module.require (node:internal/modules/cjs/loader:1463:12)
```

So after much trial and error I'm back at 8.42 using Node.js 14.21.4 for now … 🤷🏻‍♀️

**Comment by kovacs-andras** [comment]
> I happned to encounter this MODULE_NOT_FOUND error (using bundle), too. The 8.43 release doesn't have `bundle/programs/server/node_modules`. Follow steps below, and this error will be fixed.
> 
> 1. cd `bundle/programs/server/`
> 2. npm install

ありがとうございます！
It works for me. #6237

**Comment by BabyFnord** [comment]
I tried that too. Although supervisord.log and wekan.log show nothing unusual, 8.48 still gives me a 502 w/ or w/o `cd bundle/programs/server/ && npm install`. I can't get 8.42 nor 8.48 to run with Node.js 22: 
```
cd /home/USER/wekan/wekan-8.42/bundle/programs/server/ && npm install
npm WARN old lockfile
npm WARN old lockfile The npm-shrinkwrap.json file was created with an old versUSER of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! code 127
npm ERR! path /home/USER/wekan/wekan-8.42/bundle/programs/server/node_modules/fibers
npm ERR! command failed
npm ERR! command sh -c node build.js || nodejs build.js
npm ERR! node:internal/modules/cjs/loader:1386
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module '../'
npm ERR! Require stack:
npm ERR! - /home/USER/wekan/wekan-8.42/bundle/programs/server/node_modules/.bin/node-gyp
npm ERR!     at FunctUSER._resolveFilename (node:internal/modules/cjs/loader:1383:15)
npm ERR!     at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
npm ERR!     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
npm ERR!     at FunctUSER._load (node:internal/modules/cjs/loader:1192:37)
npm ERR!     at TracingChannel.traceSync (node:diagnostics_channel:328:14)
npm ERR!     at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1463:12)
npm ERR!     at require (node:internal/modules/helpers:147:16)
npm ERR!     at Object.<anonymous> (/home/USER/wekan/wekan-8.42/bundle/programs/server/node_modules/.bin/node-gyp:8:13)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1705:14) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/home/USER/wekan/wekan-8.42/bundle/programs/server/node_modules/.bin/node-gyp'
npm ERR!   ]
npm ERR! }
npm ERR!
npm ERR! Node.js v22.22.1
npm ERR! node-gyp exited with code: 1
npm ERR! Please make sure you are using a supported platform and node versUSER. If you
npm ERR! would like to compile fibers on this machine please make sure you have setup your
npm ERR! build environment--
npm ERR! Windows + OS X instructUSERs here: https://github.com/nodejs/node-gyp
npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
npm ERR! Alpine users please run: `sudo apk add python make g++`
npm ERR! sh: nodejs: command not found

npm ERR! A complete log of this run can be found in: /home/USER/.npm/_logs/2026-03-31T15_23_19_100Z-debug-0.log
```

Reverting to 8.42 and Node.js 14.21.4 again 🤷🏻‍♀️

**Comment by anyblabla** [comment]
> Hello,
>
> I’m confirming that for my installation, **v8.42** is the last stable and working version. 
> 
> Starting from **v8.43 up to v8.49** (including `latest`), the container fails to start and keeps restarting with the following error in the logs:
> 
> ```text
> Error: Cannot find module '@meteorjs/reify/lib/runtime'
> Require stack:
> - /build/programs/server/runtime.js
> - /build/main.js
> ```
> 
> It seems like a dependency or build issue within the recent Docker images. My instance is currently locked on **v8.42** to remain online: [https://wekan.blablalinux.be/](https://wekan.blablalinux.be)
> 
> Thanks for your help!

**Comment by BabyFnord** [comment]
Same here, good to know it isn't just me failing over this. As detailed [above](https://github.com/wekan/wekan/issues/6224#issuecomment-4163318017), running the suggested fix using Node.js v22.22.1 in bespoke ƒ of v8.42 and v8.48 throws errors beyond of what I can technically solve on my own. From what I see in the according [PR](https://github.com/wekan/wekan/pull/6237/changes/ea98afeb68dfacfdbec866d73461ef1d813cbfb2) it's practically the [same fix](https://github.com/wekan/wekan/issues/6224#issuecomment-4150847727) which didn't work so far.

**Comment by anyblabla** [comment]
> @BabyFnord, thanks for the feedback! 
>
> To be honest, I didn't dig any deeper on my side. As soon as I saw the crash loop, I decided to report the bug immediately and rollback to the last known stable version (v8.42) to keep my service online.
>
> For the maintainers, here is the **full error log** from the container startup to help with the debugging process:
>
> ```text
> node:internal/modules/cjs/loader:1386
>   throw err;
>   ^
> 
> Error: Cannot find module '@meteorjs/reify/lib/runtime'
> Require stack:
> - /build/programs/server/runtime.js
> - /build/main.js
>     at Function._resolveFilename (node:internal/modules/cjs/loader:1383:15)
>     at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
>     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
>     at Function._load (node:internal/modules/cjs/loader:1192:37)
>     at TracingChannel.traceSync (node:diagnostics_channel:328:14)
>     at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
>     at Module.require (node:internal/modules/cjs/loader:1463:12)
>     at require (node:internal/modules/helpers:147:16)
>     at enable (/build/programs/server/runtime.js:34:5)
>     at Object.<anonymous> (/build/main.js:4:40) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/build/programs/server/runtime.js', '/build/main.js' ]
> }
> 
> Node.js v22.22.2
> ```
>
> I hope this helps to fix the build process soon!

**Comment by telnetdoogie** [comment]
While this is marked as closed / solved, The latest version of wekan on dockerhub (`wekanteam/wekan:latest`) is still 8.48 and remains broken. If indeed it was solved with a new release (I saw there were changes in the Dockerfile for 8.49) it'd be great if that release could be built and the image pushed to dockerhub.

**Comment by BabyFnord** [comment]
@xet7 could you please have a look at this again?

**Comment by anyblabla** [comment]
> > @BabyFnord, thanks for the feedback! 
> >
> > To be honest, I didn't dig any deeper on my side. As soon as I saw the crash loop, I decided to report the bug immediately and rollback to the last known stable version (v8.42) to keep my service online.
> >
> > For the maintainers, here is the **full error log** from the container startup to help with the debugging process:
> >
> > ```text
> > node:internal/modules/cjs/loader:1386
> >   throw err;
> >   ^
> > 
> > Error: Cannot find module '@meteorjs/reify/lib/runtime'
> > Require stack:
> > - /build/programs/server/runtime.js
> > - /build/main.js
> >     at Function._resolveFilename (node:internal/modules/cjs/loader:1383:15)
> >     at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
> >     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
> >     at Function._load (node:internal/modules/cjs/loader:1192:37)
> >     at TracingChannel.traceSync (node:diagnostics_channel:328:14)
> >     at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
> >     at Module.require (node:internal/modules/cjs/loader:1463:12)
> >     at require (node:internal/modules/helpers:147:16)
> >     at enable (/build/programs/server/runtime.js:34:5)
> >     at Object.<anonymous> (/build/main.js:4:40) {
> >   code: 'MODULE_NOT_FOUND',
> >   requireStack: [ '/build/programs/server/runtime.js', '/build/main.js' ]
> > }
> > 
> > Node.js v22.22.2
> > ```
> >
> > I hope this helps to fix the build process soon!

The latest version fixes the problem for me. Everything is working perfectly again 👍

**Comment by BabyFnord** [comment]
Not for me:
```
$ node main.js
node:internal/modules/cjs/loader:1386
  throw err;
  ^

Error: Cannot find module '@meteorjs/reify/lib/runtime'
Require stack:
- /home/USER/wekan/wekan-8.54/bundle/programs/server/runtime.js
- /home/USER/wekan/wekan-8.54/bundle/main.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1383:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
    at Function._load (node:internal/modules/cjs/loader:1192:37)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
    at Module.require (node:internal/modules/cjs/loader:1463:12)
    at require (node:internal/modules/helpers:147:16)
    at enable (/home/USER/wekan/wekan-8.54/bundle/programs/server/runtime.js:34:5)
    at Object.<anonymous> (/home/USER/wekan/wekan-8.54/bundle/main.js:4:40) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/USER/wekan/wekan-8.54/bundle/programs/server/runtime.js',
    '/home/USER/wekan/wekan-8.54/bundle/main.js'
  ]
}

Node.js v22.22.2
```

Then I tried `cd bundle/programs/server/ && npm install` again:
```
$ npm install

up to date, audited 154 packages in 2s

8 packages are looking for funding
  run `npm fund` for details

13 vulnerabilities (2 low, 2 moderate, 9 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

OK, let's try again:
```
$ node main.js
node:internal/modules/cjs/loader:1386
  throw err;
  ^

Error: Cannot find module '@meteorjs/reify/lib/runtime'
Require stack:
- /home/ion/wekan/wekan-8.54/bundle/programs/server/runtime.js
- /home/ion/wekan/wekan-8.54/bundle/main.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1383:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
    at Function._load (node:internal/modules/cjs/loader:1192:37)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
    at Module.require (node:internal/modules/cjs/loader:1463:12)
    at require (node:internal/modules/helpers:147:16)
    at enable (/home/ion/wekan/wekan-8.54/bundle/programs/server/runtime.js:34:5)
    at Object.<anonymous> (/home/ion/wekan/wekan-8.54/bundle/main.js:4:40) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ion/wekan/wekan-8.54/bundle/programs/server/runtime.js',
    '/home/ion/wekan/wekan-8.54/bundle/main.js'
  ]
}

Node.js v22.22.2
```

Welp … 🤷🏻‍♀️

**Comment by xet7** [comment]
@BabyFnord 

Do NOT `npm audit fix --force`, it downgrades @meteorjs/rspack and breaks builds.  `npm audit` shows false info, it does not recognize that elliptic is  already updated to 6.6.1 with override at package.json like you can see with  `npm list elliptic`.

https://github.com/wekan/wekan/blob/main/CHANGELOG.md#v850-2026-04-03-wekan--release

**Comment by BabyFnord** [comment]
Thanks @xet7, I read that and did _not_ run `npm audit fix --force`.
