### ISSUE TITLE
cards missing after upgrade to 8.02

### ISSUE THREAD

**Issue by tograss** [wekan/wekan#5926]
First as other did I like to express my gratitude to you for providing wekan!

After upgrade to 8.02 only the cards from the first swimlane are shown. 
When opening the bord a migration window appeared as expected. However I believe the migration is incomplete / stuck. 
The logs of the app container are:

```Initializing Meteor MongoDB Integration...
Meteor MongoDB Integration already initialized
[INFO] Enabling LDAP Background Sync 
Marked board A6RNdNgdx5SEg92CL as migrated
Marked board A6RNdNgdx5SEg92CL as migrated
Marked board A6RNdNgdx5SEg92CL as migrated
Marked board A6RNdNgdx5SEg92CL as migrated
Marked board A6RNdNgdx5SEg92CL as migrated
Marked board A6RNdNgdx5SEg92CL as migrated
Marked board A6RNdNgdx5SEg92CL as migrated
Marked board A6RNdNgdx5SEg92CL as migrated
```
The line `Marked board A6RNdNgdx5SEg92CL as migrated` is then just repeated again and again.

**Comment by tograss** [comment]
Some more information:
To reproduce the bug start with a empty db and version 7.94 (I suspect earlier versions will be affected to but did not test)
create a board with two swimlanes each with a List each list with  a card

<img width="1734" height="547" alt="Image" src="https://github.com/user-attachments/assets/d0202c6c-6746-4d99-a547-12a250a81b56" />

update to 8.02
log back in and open your board 
Only one list available (and one card)

<img width="1785" height="702" alt="Image" src="https://github.com/user-attachments/assets/573da1f7-149c-402d-bc65-9509f04d90ae" />

Checking the db shows:

```
 db.cards.find({},{title:1,listId:1,boardId:1,swimlaneId:1})
[
  {
    _id: 'EY3oqngHRdni4BQpq',
    title: 'card1',
    listId: 'HB93dWNnY5bgYdtxc',
    boardId: 'dchyCFzRZWr8NivGM',
    swimlaneId: 'sK69SseWkh3tMbJvg'
  },
  {
    _id: 'QgiM4NBGySqZt6zrn',
    title: 'card2',
    listId: 'HB93dWNnY5bgYdtxc',
    boardId: 'dchyCFzRZWr8NivGM',
    swimlaneId: 'XeecF9nZxGph4zcT4'
  }
]
```
Notice how card2 has a wrong listId, the id should be different from card1. Since there is a mismatch between listId and swimlaneId card2 is not shown.

Checking lists:
```
wekan> db.lists.find()
[
  {
    _id: 'HB93dWNnY5bgYdtxc',
    title: 'List1',
    boardId: 'dchyCFzRZWr8NivGM',
    sort: 0,
    type: 'list',
    starred: false,
    archived: false,
    swimlaneId: 'sK69SseWkh3tMbJvg',
    createdAt: ISODate('2025-10-16T07:44:15.838Z'),
    updatedAt: ISODate('2025-10-16T07:47:48.667Z'),
    modifiedAt: ISODate('2025-10-16T07:47:48.654Z'),
    wipLimit: { value: 1, enabled: false, soft: false },
    collapsed: false
  }
]
```
shows List2 is missing. Recreating List2 and updating listId for card2 brings the board back in the correct state

**Comment by Tuphal** [comment]
same here. Log is spammed with "Migration" entries.
And 4 of my 5 swimlanes are empty.

updated from 7.92 -> 8.02

EDIT:
happens also when updating from 7.92 -> 7.98. This time without Migration log entries, only two"migrate-lists-to-per-swimlane migration" entries (Start and finished). Need to restore again :/


EDIT2:
upgraded v7.92 -> 7.94 -> 7.96 -> 7.97  without issues.
update to v7.98 will wipe the entries.

**Comment by xet7** [comment]
Moved to #5939

**Comment by tograss** [comment]
I'm still seeing the exact same behavior when using 8.04

**Comment by tograss** [comment]
OK I thing I understand the problem a bit better. Before 7.97 all lists are _shared_ lists . Adding a list to a lane ads them to all lanes, modifying the title of one list modifies the title of all lists. This changes with 7.98+ all new lists become _single_ lists. Adding a list to a lane does not add them to other lanes, you cant modify the titles in one go. Beside the migration problems I think some users like the pre 7.97 way. Imaging having a board with 20 lanes and wanting to add a new list for all lanes.

I can think of different ways to move forward:
**a.) decide to not support shared lists anymore**
This would require a proper migration. Create new lists in db for each lane and assign cards to the new list.
Maybe shared lists can come back in the future
**b.) support shared lists**
Of course there are a lot of ways this could be done. 
I would just an attribute to lists, maybe is_shared -> if false new behavior / if true or non existent old behavior 
For now new lists are created as _single_ lists, but in the future there could be ui features properly allowing to deal with the different type of lists (creation , conversion and a visible distinction) 
**c.) rollback _single_ lists**
rollback the change and think / discuss this feature a bit more. In the meantime release the security fixes separate. 

Could you tell if I'm understanding the problem correctly and which option you plan to choose?

**Comment by Tuphal** [comment]
same behaviour for me.
I tried fixxing it with the `db.lists.updateMany` commands from issue [#5939](https://github.com/wekan/wekan/issues/5939), without success.

**Comment by tograss** [comment]
I think the command is only for downgrading back to 7.97.

**Comment by s8321414** [comment]
Still can't see cards in swimlane view for v8.06.

**Comment by tograss** [comment]
@xet7 could you reopen this issue ?
since even with v8.06 the problem persists and is still reproducible coming from a clean install of v7.94

**Comment by tograss** [comment]
When updating from 8.06 to 8.07 the following error appears

`wekan-app  | Found mismatched card: JiyjSRn6H83ez4r8n, listId: oEEpCSPGCmnJXmAfG, card swimlaneId: 7spuecTFmLXw8sqXg, list swimlaneId: FmGTGe8ZSCyHFZLWC
wekan-app  | Starting fix missing lists migration for board yW8B2Pctzd9jFBp6A
wekan-app  | Error executing fix missing lists migration for board yW8B2Pctzd9jFBp6A: TypeError: ReactiveCache.getCollection is not a function
wekan-app  |     at server/migrations/fixMissingListsMigration.js:161:45
wekan-app  |     at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
wekan-app  | Exception while invoking method 'fixMissingListsMigration.execute' TypeError: ReactiveCache.getCollection is not a function
wekan-app  |     at server/migrations/fixMissingListsMigration.js:161:45
wekan-app  |     at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
wekan-app  |  => awaited here:
wekan-app  |     at Function.Promise.await (/build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
wekan-app  |     at packages/meteor.js:367:22
wekan-app  |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
wekan-app  |     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
wekan-app  |     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1935:18)
wekan-app  |     at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:808:38)
wekan-app  |     at packages/meteor.js:365:18
wekan-app  |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
wekan-app  |     at packages/ddp-server/livedata_server.js:827:46
wekan-app  |     at new Promise (<anonymous>)
wekan-app  |     at Session.method (packages/ddp-server/livedata_server.js:775:23)
wekan-app  |     at packages/ddp-server/livedata_server.js:639:43
`

Have not tested wit a clean version from 7.94 yet

**Comment by Tuphal** [comment]
Migrated from v7.97 to 8.07. At the first glace it seems all cards are visible.
THANK YOU VERY MUCH !!

But in the log are some repeating attemps for fixxing cards:
```
2025-10-21T06:29:44.205165989Z Marked board dH6YEzf9iL9okbCga as migrated
2025-10-21T06:29:46.916192522Z Found mismatched card: ZxPQL8dTzH2eTnKEQ, listId: LDtXp8gF8qBQnDdEy, card swimlaneId: ojXRCtp9JxkmHyzjF, list swimlaneId: ivdMD5Enjk6HpjtNw
2025-10-21T06:29:46.947349865Z Starting fix missing lists migration for board dH6YEzf9iL9okbCga
2025-10-21T06:29:46.994432882Z Error executing fix missing lists migration for board dH6YEzf9iL9okbCga: TypeError: ReactiveCache.getCollection is not a function
2025-10-21T06:29:46.994459129Z     at server/migrations/fixMissingListsMigration.js:161:45
2025-10-21T06:29:46.994461211Z     at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
2025-10-21T06:29:46.994829964Z Exception while invoking method 'fixMissingListsMigration.execute' TypeError: ReactiveCache.getCollection is not a function
2025-10-21T06:29:46.994835425Z     at server/migrations/fixMissingListsMigration.js:161:45
2025-10-21T06:29:46.994837313Z     at /build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
2025-10-21T06:29:46.994838754Z  => awaited here:
2025-10-21T06:29:46.994840213Z     at Function.Promise.await (/build/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
2025-10-21T06:29:46.994841593Z     at packages/meteor.js:367:22
2025-10-21T06:29:46.994842828Z     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
2025-10-21T06:29:46.994844091Z     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
2025-10-21T06:29:46.994845444Z     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1935:18)
2025-10-21T06:29:46.994846725Z     at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:808:38)
2025-10-21T06:29:46.994848065Z     at packages/meteor.js:365:18
2025-10-21T06:29:46.994849245Z     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
2025-10-21T06:29:46.994900758Z     at packages/ddp-server/livedata_server.js:827:46
2025-10-21T06:29:46.994903934Z     at new Promise (<anonymous>)
2025-10-21T06:29:46.994905392Z     at Session.method (packages/ddp-server/livedata_server.js:775:23)
2025-10-21T06:29:46.994906682Z     at packages/ddp-server/livedata_server.js:639:43
```
